### ISSUE TITLE
DEMO: New ZF2modules site with rating and comments!

### ISSUE THREAD

**Issue by alexz707** [zendframework/modules.zendframework.com#305]
Hi!

We would like to show you the zf2 modules site which we developed. It includes ratings (currently based on user-rating), comments, filters and tags!

See attached screenshot or you can try it on the following server:

http://54.175.68.84/

Due to many changes in the source we created a new repository under:

https://github.com/PHP-Unlimited/ZF2-Modules-Site

Please let us know what you think! It would be awesome if this would be the new modules page!

Herbert // Alex // PHP Unlimited
PS: it's only a beta and maybe includes bugs ;)
![bildschirmfoto 2015-01-13 um 13 38 27](https://cloud.githubusercontent.com/assets/562324/5720800/7ceb6a96-9b29-11e4-9185-34ffbe834802.png)

**Comment by gianarb** [comment]
wow!

**Comment by alexz707** [comment]
Just a little update and some technical details:

Currently the system is on an amazon ec2 instance (c4 large, us-east-1).
The system includes Apache 2.4, PHP 5.6 + OPC , Elasticsearch 1.3.6, MariaDB 5.5, Memcached.
It supports fuzzy fulltextsearch, filtering by tags, users, requirements, modulename and rating.

The continuous delivery process works via Github, Scrutinizer,  Amazon Codedeploy and is triggered by a git commit.

We would appreciate your feedback, missing features or bugs!

@Ocramius @GeeH @EvanDotPro @localheinz @ins0 @Hounddog 
I already talked to 2 guys of you and I hope we get some feedback from the others too!

Maybe you can play around, register modules and rate modules  as well as discuss our project when you meet at php benelux :-)

@gianarb thx ;)

Herbert // Alex // PHP Unlimited

**Comment by GeeH** [comment]
This looks very good, HOWEVER, we don't have any interest in replacing the entire site with what you've coded. The appropriate way to introduce these features is with a series of pull requests. Thanks for the effort but it's currenty unusable.

**Comment by herbert-roth** [comment]
This site was a way of passing the time over the Chrismas holidays. So i dont spend any time in thinking of backwards compatibility. 
To upgrade with a series of pull requests i have to start all over again, but holidays are over now. 

So we keep the test server up and the repos online until the end of the month.
If anyone is interested in this project or parts of it, feel free to use it.

Thanks for taking the time to look at this project.

**Comment by gianarb** [comment]
@herbert-roth maybe you can send a PR with first step of graphic improvements without ranking and discussion..
Into the next steps this new features :+1: For you is a possible flow?

**Comment by ins0** [comment]
as geeh and gianarb allready said, i really like this design and would love to see this in a couple of weeks in master.

**Comment by localheinz** [comment]
I think it's a great idea to contribute, but I'm not so sure what you guys thought would be the way of integrating your changes into this repository. 

First of all, I don't get why you split the repository instead of just forked it, maybe you can elaborate?

Your commit history is currently 68 commits, how did that happen? Did you rewrite the history?

**Comment by herbert-roth** [comment]
@localheinz I developed this on my machine locally, so there is no long commit history available. 
We started to commit after my colleague and me worked together on some bugs and the continuous delivery process.

The reason why i am split the repositories was, because i know it would be a too complex job to integrate it into the old repository via pull request. 
We don’t use a DB anymore to store module relevant data. 
All data is stored in elasticsearch now to enable the filters, 
aggregations(facets) and the more flexible and powerful fulltext-search.

So i started from scratch with the ZfModule (except some reused parts of one or two views) 
and based on this i also had to rewrite most of the User module.

However we thought it would not be such a problem to use our base as the new site because in the description of your repository it states „(Eventual) home….“.

Of course we can put all our changes into one pull request, 
but this will not work without a one time migration of existing data into the search server 
and installation of some additionale components like java, elasticsearch, memcached and php 5.6
We also know that our source is more beta than productive and some unit tests are missing but its working...

**Comment by ins0** [comment]
@herbert-roth everyone here appreciate your work but it is hard now to review a full project. 

please don't get me wrong but from my point of view this repo lacks in code quality and missed code reviews as u start developing without let someone notice here or open a issue/pr. 

the benefits of this repo are its well known developers and there suggestions for you and the project itself.

maybe you can start thinking how to separate your project into small chunks and pr against this repository. i really love your current state and would love to see this progress on modules.zendframework.com.

**Comment by alexz707** [comment]
@ins0  can you give us some more details about the alleged lack of code quality ? We really want to improve ourselves if there is something wrong ;) 

Normally I would say PR are the way to do a rewrite BUT when the data needs to be migrated as well as the infrastructure is changed (elasticsearch) it's not really possible. So the small chunks wouldn't be working too...
Or do you have  solution for that ?

**Comment by ins0** [comment]
@alexz707 i'm not one of the well know and experienced developers here but these files catch my attention

https://github.com/PHP-Unlimited/ZF2-Modules-Site/blob/master/module/ZfModule/src/ZfModule/Connection/Client/SingleServer.php#L27
why the ``if else`` for the ``new Client`` if only the bool param changes

https://github.com/PHP-Unlimited/ZF2-Modules-Site/blob/master/module/Core/src/Core/Utils/Md5.php#L19
is this file needed? exec?

https://github.com/PHP-Unlimited/ZF2-Modules-Site/blob/master/module/Core/Module.php#L33
maybe create a listener class if the logic here gets more complex

but to get notice on these little things through pr i like the most :)

**Comment by gianarb** [comment]
@alexz707 code refactoring is a very difficult work :) A big feature is a problem for the maintainers.. This feature leaves the old history, the merge is a big problem.

ElasticSearch is a good idea but it's not the priorities now, in more who manage in production this service?

For me this update require answers at questions not made..
Can you help this project with little part of your code step by step?

**Comment by EvanDotPro** [comment]
As a side note, I just want to clarify that my team at Roave and I manage the production env for the modules site currently, and we are _more_ than happy to work with contributors to deploy any necessary new technologies that aren't already in the stack, time permitting, and as long as it's the right tool for the job. :)

**Comment by ins0** [comment]
:+1:

**Comment by gianarb** [comment]
@EvanDotPro perfect! :) Thanks

**Comment by gianarb** [comment]
In my opinion this issue is inapplicable

**Comment by GeeH** [comment]
Closing this, we'd happily take this code as a series of PR.
